// src/config-writer.ts
// Writes System/VaultForge/config.md from current plugin settings.
//
// config.md is plugin-owned infrastructure — never hand-edited.
// It is regenerated every time settings change so it always reflects
// the current state of data.json.
//
// The note is intentionally minimal frontmatter + a JSON block.
// It is not schema-governed and not lint-validated.

import { App, TFile, normalizePath } from "obsidian";
import type { VaultForgeSettings } from "./settings";
import { getVaultPaths } from "./vault-paths";

/**
 * Writes (or overwrites) System/VaultForge/config.md with the
 * current plugin settings rendered as a readable JSON block.
 */
export async function writeConfigNote(
  app: App,
  settings: VaultForgeSettings
): Promise<void> {
  const paths = getVaultPaths(settings);
  const configPath = normalizePath(paths.configMd);

  const now = new Date().toISOString();

  const content = buildConfigNote(settings, now);

  // Ensure the VaultForge directory exists
  const dir = normalizePath(paths.vaultForge);
  if (!app.vault.getAbstractFileByPath(dir)) {
    await app.vault.createFolder(dir);
  }

  const existing = app.vault.getAbstractFileByPath(configPath);

  if (existing instanceof TFile) {
    await app.vault.modify(existing, content);
  } else {
    await app.vault.create(configPath, content);
  }
}

function buildConfigNote(settings: VaultForgeSettings, generatedAt: string): string {
  const config = {
    identity: {
      type_field: settings.typeField,
      status_field: settings.statusField,
      tags_field: settings.tagsField,
      created_field: settings.createdField,
      updated_field: settings.updatedField,
    },
    paths: {
      system_folder: settings.systemFolder,
      vault_forge_folder: settings.vaultForgeFolder,
      schema_note: `${settings.schemaNoteFolder}/${settings.schemaNoteFile}`,
      exports_folder: settings.exportsFolder,
      patches_folder: settings.patchesFolder,
      lint_runs_folder: settings.lintRunsFolder,
      inbox_folder: settings.inboxFolder,
      patterns_folder: settings.patternsFolder,
    },
    patch: {
      backup_enabled: settings.patchBackupEnabled,
      backup_location: "System/VaultForge/Patches/Backups/",
      generate_restore_manifest: settings.patchGenerateManifest,
      default_file: settings.patchDefaultFile,
      auto_lint_after_apply: settings.patchAutoLintAfterApply,
      auto_maintenance_after_apply: settings.patchAutoMaintenanceAfterApply,
    },
    lint: {
      strict_mode: settings.lintStrictMode,
      lint_run_retention_count: settings.lintRunRetentionCount,
    },
    maintenance: {
      backup_retention_days: settings.backupRetentionDays,
      inbox_retention_days: settings.inboxRetentionDays,
      lint_history_retention_days: settings.lintHistoryRetentionDays,
      lint_history_max_entries: settings.lintHistoryMaxEntries,
      patch_report_retention_count: settings.patchReportRetentionCount,
    },
  };

  return [
    "---",
    "vault_forge_config: true",
    `generated: ${generatedAt}`,
    "---",
    "",
    "> [!note] Vault Forge Configuration",
    "> This file is generated by the Vault Forge plugin and reflects the current",
    "> plugin settings. Do not edit manually — use Settings → Vault Forge instead.",
    "",
    "```json",
    JSON.stringify(config, null, 2),
    "```",
    "",
  ].join("\n");
}
